# Generated by Django 4.0.2 on 2022-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('confirm', 'confirm'), ('cancel', 'cancel')], max_length=100, null=True),
        ),
    ]
